"""Request/response models for the RAG query endpoint.

The response exposes the useful, client-facing parts of the Sprint 8
``RagResponse``: the generated answer, the repository and question, the
retrieved sources with file paths and line ranges, and model/provider
metadata. Raw embedding vectors and ChromaDB objects are never exposed.
"""

from typing import List, Optional

from pydantic import BaseModel, ConfigDict, Field, field_validator


class RagQueryRequest(BaseModel):
    """Request model for asking a question over an indexed repository.

    Attributes:
        repository_name: Repository to search within (must be indexed).
        question: Natural-language question about the repository.
        top_k: Maximum number of retrieved sources to fetch (optional;
            a small positive integer, defaulted by the service).
    """

    repository_name: str = Field(
        ...,
        description="Name of the indexed repository to query",
        examples=["demo-repository"],
        max_length=200,
    )
    question: str = Field(
        ...,
        description="Natural-language question about the repository code",
        examples=["Where is user authentication handled?"],
        max_length=1000,
    )
    top_k: Optional[int] = Field(
        default=None,
        description=(
            "Maximum number of retrieved sources to fetch. Must be a "
            "positive integer. Defaults to the service configuration."
        ),
        ge=1,
        le=20,
    )

    @field_validator("repository_name")
    @classmethod
    def validate_repository_name(cls, value: str) -> str:
        """Reject empty/whitespace-only repository names."""
        trimmed = value.strip()
        if not trimmed:
            raise ValueError("repository_name must not be empty or whitespace")
        return trimmed

    @field_validator("question")
    @classmethod
    def validate_question(cls, value: str) -> str:
        """Reject empty/whitespace-only questions."""
        trimmed = value.strip()
        if not trimmed:
            raise ValueError("question must not be empty or whitespace")
        return trimmed

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "repository_name": "demo-repository",
                "question": "Where is user authentication handled?",
                "top_k": 5,
            }
        }
    )


class RagQuerySource(BaseModel):
    """A single retrieved source used to ground the answer.

    Attributes:
        file_path: Path of the source file, relative to the repository root.
        language: Programming language of the source.
        start_line: Starting line of the retrieved chunk (1-based).
        end_line: Ending line of the retrieved chunk (1-based).
        relevance_score: Normalized relevance in [0, 1]; higher is more
            relevant.
    """

    file_path: str = Field(
        ...,
        description="Source file path relative to the repository root",
    )
    language: str = Field(
        ...,
        description="Programming language of the source",
    )
    start_line: int = Field(
        ...,
        description="Starting line of the chunk (1-based)",
        ge=1,
    )
    end_line: int = Field(
        ...,
        description="Ending line of the chunk (1-based)",
        ge=1,
    )
    relevance_score: float = Field(
        ...,
        description="Normalized relevance score in [0, 1]; higher = more relevant",
        ge=0.0,
        le=1.0,
    )

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "file_path": "src/auth.py",
                "language": "Python",
                "start_line": 10,
                "end_line": 25,
                "relevance_score": 0.87,
            }
        }
    )


class RagQueryResponse(BaseModel):
    """Response model for a RAG query.

    Attributes:
        answer: The grounded answer generated by the LLM provider.
        repository_name: Repository the question was asked about.
        question: The user's question.
        sources: Retrieved sources used to ground the answer (file paths,
            line ranges, relevance). Never includes raw embedding vectors.
        insufficient_context: True when no relevant context was retrieved and
            the system explicitly declined to fabricate an answer.
        model_name: Name of the model that produced the answer, if known.
        provider_name: Name of the provider that produced the answer.
        retrieved_count: Number of retrieved results passed to the prompt
            builder (after the relevance gate).
        context_included_count: Results that fit the context budget.
    """

    answer: str = Field(
        ...,
        description="Grounded answer text",
    )
    repository_name: str = Field(
        ...,
        description="Repository the question was asked about",
    )
    question: str = Field(
        ...,
        description="The user's question",
    )
    sources: List[RagQuerySource] = Field(
        default_factory=list,
        description="Retrieved sources used to ground the answer",
    )
    insufficient_context: bool = Field(
        default=False,
        description="True when no relevant context was retrieved",
    )
    model_name: Optional[str] = Field(
        default=None,
        description="Model that produced the answer",
    )
    provider_name: Optional[str] = Field(
        default=None,
        description="Provider that produced the answer",
    )
    retrieved_count: int = Field(
        default=0,
        description="Retrieved results used for the answer",
        ge=0,
    )
    context_included_count: int = Field(
        default=0,
        description="Retrieved results that fit the context budget",
        ge=0,
    )

    model_config = ConfigDict(
        protected_namespaces=(),
        json_schema_extra={
            "example": {
                "answer": "User authentication is handled in src/auth.py lines 10-25.",
                "repository_name": "demo-repository",
                "question": "Where is user authentication handled?",
                "sources": [
                    {
                        "file_path": "src/auth.py",
                        "language": "Python",
                        "start_line": 10,
                        "end_line": 25,
                        "relevance_score": 0.87,
                    }
                ],
                "insufficient_context": False,
                "model_name": "mock-llm",
                "provider_name": "mock",
                "retrieved_count": 1,
                "context_included_count": 1,
            }
        }
    )
